language: python
python: "3.7"
    
 # don't clone more than necessary
git:
  depth: 1

branches:
  only:
    - testcase
    - master

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

 # Install dependencies
install:
  - pip install codecov 
  - pip install -r requirements.txt
    
 # script to run tests. Script can have many commands, one per line.
script: 
  - coverage run manage.py test

after_success:
  - codecov